name:                arbitrary-interpreter
version:             1.0.0.0
github:              "kwie98/arbitrary-interpreter"
license:             BSD3
author:              "Konrad Wienecke"
maintainer:          "konrad.wienecke@mac.com"
copyright:           "2020 Konrad Wienecke"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/arbitrary-interpreter#readme>

dependencies:
- base >= 4.7 && < 5
- vector
- unordered-containers
- containers
- hspec
- directory
- filepath
- split
- docopt

library:
  source-dirs: src

executables:
  arbipreter:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - arbitrary-interpreter

tests:
  arbitrary-interpreter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - arbitrary-interpreter
